#!/bin/bash
########################################################################
#  Copyright (C) 2010 Tomas Kindahl                                    #
########################################################################
#  This file is part of mkmap                                          #
#                                                                      #
#  mkmap is free software: you can redistribute it and/or modify it    #
#  under the terms of the GNU General Public License as published by   #
#  the Free Software Foundation, either version 3 of the License, or   #
#  (at your option) any later version.                                 #
#                                                                      #
#  mkmap is distributed in the hope that it will be useful,            #
#  but WITHOUT ANY WARRANTY; without even the implied warranty of      #
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the       #
#  GNU General Public License for more details.                        #
#                                                                      #
#  You should have received a copy of the GNU General Public License   #
#  along with mkmap. If not, see <http://www.gnu.org/licenses/>.       #
########################################################################/

for f in *.{c,h}
do
    if ! grep Copyright $f > /dev/null
    then
        echo File $f lacks copyright info
    fi
done

